name: apptex_chat
description: This Package is for making the chat system more easy and user friendly. and control chat features within one click.
version: 1.0.2
homepage: https://github.com/apptexsolutions/apptex_chat

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Dependencies
  get: ^4.6.1
  image_picker: ^0.8.5
  cloud_firestore: ^3.1.15
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16

  permission_handler: ^10.1.0
  audio_waveforms: ^0.1.5+1
  # audio_session: ^0.1.10
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
 
flutter: